"""
Bridge Flow - Pairing Manager (Phase 9: Secure Peer Pairing)

Being on the same Wi-Fi is NOT trust. A device must go through this
out-of-band pairing flow before it is allowed to send a TRANSFER_REQUEST
(enforced in transfer/tcp_server.py via database.dao.is_trusted()).

Flow (matches the protocol in transfer/protocol.py):
  1. Initiator connects to a discovered peer and sends PAIR_REQUEST.
  2. Receiver generates a random 6-digit code and surfaces it in ITS
     OWN UI (never sent over the wire during this step).
  3. The human reads that code off Device B's screen and types it into
     Device A's UI.
  4. Initiator sends PAIR_CONFIRM{code}. If it matches what the
     receiver generated, both sides are marked trusted and a shared
     Fernet key (generated by the receiver) is handed to the initiator
     to encrypt future messages between this specific pair.

Known simplification (documented honestly for the project report):
the shared key is transmitted once, in the clear, over the same TCP
connection used for code confirmation. This is a trust-on-first-use
(TOFU) model, the same class of assumption SSH uses for unknown hosts.
A stronger design would derive the key from a Diffie-Hellman exchange
authenticated by the pairing code (like Bluetooth's numeric comparison
pairing) - documented in the report as a "Future Scope" improvement.
"""

import secrets
import time

from database import dao
from security.crypto_utils import generate_shared_key
from utils.logger import get_logger

logger = get_logger("pairing")

CODE_EXPIRY_SECONDS = 120
MAX_WRONG_ATTEMPTS = 3        # a code dies after this many wrong guesses
MAX_REQUESTS_PER_MINUTE = 5   # global cap on incoming pairing requests

_recent_requests: list[float] = []

# In-memory table of pairing codes currently being shown to the user,
# keyed by the device_id of whoever is TRYING to pair with us.
_pending_codes: dict[str, dict] = {}


def generate_pairing_code(requester_device_id: str) -> str | None:
    """Called when we (the receiver) get a PAIR_REQUEST. Returns the
    code to display in our own UI for the human to read aloud/type."""
    now = time.time()
    _recent_requests[:] = [t for t in _recent_requests if now - t < 60]
    if len(_recent_requests) >= MAX_REQUESTS_PER_MINUTE:
        logger.warning("Too many pairing requests - ignoring (possible guessing attempt)")
        return None
    _recent_requests.append(now)

    # secrets (not random) - pairing codes are security-relevant
    code = f"{secrets.randbelow(1_000_000):06d}"
    _pending_codes[requester_device_id] = {"code": code, "created_at": now, "wrong_attempts": 0}
    logger.info(f"Pairing code generated for request from {requester_device_id[:8]}...: {code}")
    return code


def verify_pairing_code(requester_device_id: str, submitted_code: str) -> bool:
    entry = _pending_codes.get(requester_device_id)
    if not entry:
        return False
    if time.time() - entry["created_at"] > CODE_EXPIRY_SECONDS:
        del _pending_codes[requester_device_id]
        return False
    is_match = secrets.compare_digest(entry["code"], submitted_code)
    if is_match:
        del _pending_codes[requester_device_id]
        return True
    entry["wrong_attempts"] += 1
    if entry["wrong_attempts"] >= MAX_WRONG_ATTEMPTS:
        del _pending_codes[requester_device_id]
        logger.warning(f"Pairing code for {requester_device_id[:8]}... burned after too many wrong guesses")
    return False


def complete_pairing(device_id: str, device_name: str, ip: str) -> str:
    """Called on the receiver's side after a code match. Creates/updates
    the device row as trusted and returns the new shared key so it can
    be sent back to the initiator."""
    dao.upsert_device(device_id, device_name, ip)
    shared_key = generate_shared_key()
    dao.set_device_trusted(device_id, shared_key)
    logger.info(f"Device {device_name} ({device_id[:8]}...) is now trusted")
    return shared_key


def list_pending_incoming_requests() -> list[dict]:
    """For the Pairing UI: 'someone is asking to pair, here's the code
    to read out / display so the other device's user can enter it.'"""
    now = time.time()
    return [
        {"requester_device_id": device_id, "code": entry["code"],
         "expires_in": max(0, int(CODE_EXPIRY_SECONDS - (now - entry["created_at"])))}
        for device_id, entry in _pending_codes.items()
        if now - entry["created_at"] <= CODE_EXPIRY_SECONDS
    ]


def store_received_key(device_id: str, device_name: str, ip: str, shared_key: str):
    """Called on the initiator's side once the receiver confirms pairing
    and sends back the shared key."""
    dao.upsert_device(device_id, device_name, ip)
    dao.set_device_trusted(device_id, shared_key)
